[package]
name = "forward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.11"
reqwest = {version = "0.12.5", features = ["blocking"]}
url = "2.5.2"